site_name: DoLearn
# make it with a readthedocs theme
theme: readthedocs
extra:
  version: v1.0.0

nav:
  - Quickstart:
    - Quickstart: quickstart.ipynb

plugins:
  - search:
  - mknotebooks:
  - mkdocstrings:
      handlers:
        python:
          options:
            filters: ["!^_"]  # Exclude anything starting with "_"
            show_root_toc_entry: false